name: khdma
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  http: ^0.13.4
  get_storage:
  path_provider: 2.0.2
  flutter_form_builder: ^6.1.0+1
  carousel_slider: ^4.1.1
  image_picker: ^0.8.4+4
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  dropdown_search: 5.0.2
  intl: ^0.17.0
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


  flutter_launcher_icons:
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo/logo.png"
  #flutter pub run flutter_launcher_icons:main


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/